# © 2019 - today Numigi (tm) and all its contributors (https://bit.ly/numigiens)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "account_recording_dimensions",
        "artist",
        "artist_url_link",
        "contact_birth_city",
        "crm_production_title",
        "crm_musical_relation",
        "musical_artwork",
        "musical_catalog",
        "partner_organization_membership",
        "product_musical_relation",
        "recording",
        "recording_analytic",
        "recording_artist",
        "recording_contributor",
        "recording_credential_format",
        "recording_external_revenue",
        "recording_external_revenue_account",
        "recording_genre",
        "recording_lang",
        "recording_lyrics",
        "recording_musical_artwork",
        "recording_platform",
        "recording_status",
        "recording_subgenre",
        "recording_tag",
        "recording_url_link",
        "recording_version",
        "show_appearance_type",
        "show_place",
        "show_project",
        "show_project_access",
        "show_project_artwork",
        "show_project_custom_view",
        "show_project_fee",
        "show_project_list",
        "show_project_promotion",
        "show_project_role",
        "show_project_sale",
        "show_project_sold_tickets",
    ],
    "installable": True,
}
